# Generated by Django 5.2.4 on 2025-08-01 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='kategori',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='prioritas',
            field=models.CharField(choices=[('low', 'Rendah'), ('medium', 'Sedang'), ('high', 'Tinggi')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.BooleanField(default=False, help_text='Centang jika project sudah selesai'),
        ),
    ]
