# Generated by Django 5.2.4 on 2025-08-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_project_kategori_project_prioritas_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('perencanaan', 'Masa Perencanaan'), ('pelaksanaan', 'Masa Pelaksanaan'), ('pemeriksaan', 'Masa Pemeriksaan'), ('selesai', 'Selesai')], default='Masa Perencanaan', max_length=20),
        ),
    ]
