# Generated by Django 5.2.4 on 2025-08-04 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_project_anggaran_owner_project_index_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='prioritas',
        ),
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
    ]
