# Generated by Django 5.2.4 on 2025-08-08 09:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_project_prioritas_remove_project_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='anggaran_owner',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='deskripsi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='index_project',
            field=models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='lokasi_project',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='nama_client',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='sumber_dana',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='tahun_project',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['owner', '-updated_at'], name='dashboard_p_owner_i_b9b4a9_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['nama'], name='dashboard_p_nama_d1354c_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['tahun_project'], name='dashboard_p_tahun_p_2075a2_idx'),
        ),
    ]
