# Generated by Django 5.2.4 on 2025-11-05 21:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0007_project_timeline_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="tahun_project",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="tanggal_mulai",
            field=models.DateField(
                default=django.utils.timezone.now,
                help_text="Tanggal mulai pelaksanaan project (wajib, tahun akan diambil dari field ini)",
                verbose_name="Tanggal Mulai Pelaksanaan",
            ),
        ),
    ]
