# Generated by Django 5.2.4 on 2025-11-05 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0008_alter_project_tahun_project_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="tanggal_mulai",
            field=models.DateField(
                help_text="Tanggal mulai pelaksanaan project (wajib, tahun akan diambil dari field ini)",
                verbose_name="Tanggal Mulai Pelaksanaan",
            ),
        ),
    ]
