# Generated by Django 5.2.2 on 2026-01-08 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_project_week_boundaries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='week_end_day',
            field=models.PositiveSmallIntegerField(blank=True, default=6, help_text='Angka hari akhir minggu (0=Senin, 1=Selasa ... 6=Minggu) untuk siklus progress mingguan', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='week_start_day',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='Angka hari awal minggu (0=Senin, 1=Selasa ... 6=Minggu) untuk siklus progress mingguan', null=True),
        ),
    ]
