# Generated by Django 5.2.15 on 2026-08-18 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_project_schedule_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ket_client2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='sebutan_client',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
