# Generated by Django 5.2.11 on 2026-09-29 09:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_project_ket_client2_project_sebutan_client'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tanggal_akhir_tambahan',
            field=models.DateField(blank=True, help_text='Tanggal akhir pencatatan realisasi setelah akhir waktu kerja kontrak', null=True, verbose_name='Akhir Tambahan Waktu Kerja'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(('tanggal_akhir_tambahan__isnull', True), models.Q(('tanggal_akhir_tambahan__gt', models.F('tanggal_selesai')), ('tanggal_selesai__isnull', False)), _connector='OR'), name='project_additional_end_after_contract_end'),
        ),
    ]
