# Generated by Django 5.2.4 on 2026-01-15 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='subscription_end_date',
            field=models.DateTimeField(blank=True, help_text='When the paid subscription ends', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='subscription_status',
            field=models.CharField(choices=[('TRIAL', 'Trial'), ('PRO', 'Pro'), ('EXPIRED', 'Expired')], default='TRIAL', help_text='Current subscription status', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='trial_end_date',
            field=models.DateTimeField(blank=True, help_text='When the trial period ends', null=True),
        ),
    ]
