# Generated by Django 5.2.11 on 2026-02-17 02:44

from django.db import migrations, models


def mark_existing_trial_consumers(apps, schema_editor):
    CustomUser = apps.get_model("accounts", "CustomUser")
    CustomUser.objects.filter(
        models.Q(trial_end_date__isnull=False)
        | models.Q(subscription_end_date__isnull=False)
        | models.Q(subscription_status__in=["PRO", "EXPIRED"])
    ).update(trial_used_once=True)


def unmark_existing_trial_consumers(apps, schema_editor):
    CustomUser = apps.get_model("accounts", "CustomUser")
    CustomUser.objects.update(trial_used_once=False)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_subscription_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='trial_used_once',
            field=models.BooleanField(default=False, help_text='Marks whether free trial has been consumed once for this account.'),
        ),
        migrations.RunPython(mark_existing_trial_consumers, unmark_existing_trial_consumers),
    ]
