# Generated by Codex on 2026-02-08

from django.db import migrations, models
import django.db.models.deletion


def seed_default_entitlements(apps, schema_editor):
    SubscriptionPlan = apps.get_model("subscriptions", "SubscriptionPlan")
    SubscriptionFeature = apps.get_model("subscriptions", "SubscriptionFeature")
    PlanFeatureEntitlement = apps.get_model("subscriptions", "PlanFeatureEntitlement")

    features = [
        ("write_access", "Write Access", "Hak melakukan operasi write (POST/PUT/PATCH/DELETE)."),
        ("export_pdf", "Export PDF", "Hak export PDF (expired dapat watermark)."),
        ("export_excel_word", "Export Excel/Word", "Hak export Excel/Word (umumnya PRO)."),
        ("export_clean", "Clean Export", "Hak export tanpa watermark."),
        ("pro_only", "PRO-only Feature", "Hak fitur premium yang khusus PRO."),
    ]
    feature_map = {}
    for code, name, description in features:
        feature, _ = SubscriptionFeature.objects.get_or_create(
            code=code,
            defaults={
                "name": name,
                "description": description,
                "is_active": True,
            },
        )
        feature_map[code] = feature

    default_matrix = {
        "TRIAL": {
            "write_access": "allow",
            "export_pdf": "deny",
            "export_excel_word": "deny",
            "export_clean": "deny",
            "pro_only": "deny",
        },
        "PRO": {
            "write_access": "allow",
            "export_pdf": "allow",
            "export_excel_word": "allow",
            "export_clean": "allow",
            "pro_only": "allow",
        },
        "EXPIRED": {
            "write_access": "deny",
            "export_pdf": "watermark",
            "export_excel_word": "deny",
            "export_clean": "deny",
            "pro_only": "deny",
        },
    }

    for status, features_by_status in default_matrix.items():
        for feature_code, access_level in features_by_status.items():
            PlanFeatureEntitlement.objects.get_or_create(
                feature=feature_map[feature_code],
                plan=None,
                subscription_status=status,
                defaults={
                    "access_level": access_level,
                    "note": "Default status matrix",
                },
            )

    pro_feature_codes = [
        "write_access",
        "export_pdf",
        "export_excel_word",
        "export_clean",
        "pro_only",
    ]
    for plan in SubscriptionPlan.objects.all():
        for feature_code in pro_feature_codes:
            PlanFeatureEntitlement.objects.get_or_create(
                feature=feature_map[feature_code],
                plan=plan,
                subscription_status="PRO",
                defaults={
                    "access_level": "allow",
                    "note": "Plan-level PRO default",
                },
            )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionFeature",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="PlanFeatureEntitlement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("subscription_status", models.CharField(choices=[("TRIAL", "Trial"), ("PRO", "Pro"), ("EXPIRED", "Expired")], max_length=20)),
                ("access_level", models.CharField(choices=[("deny", "Deny"), ("allow", "Allow"), ("watermark", "Allow with Watermark")], default="deny", max_length=20)),
                ("note", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("feature", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="entitlements", to="subscriptions.subscriptionfeature")),
                ("plan", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="feature_entitlements", to="subscriptions.subscriptionplan")),
            ],
            options={
                "ordering": ["feature__code", "subscription_status", "plan__duration_months"],
            },
        ),
        migrations.AddConstraint(
            model_name="planfeatureentitlement",
            constraint=models.UniqueConstraint(fields=("feature", "plan", "subscription_status"), name="uniq_entitlement_feature_plan_status"),
        ),
        migrations.RunPython(seed_default_entitlements, noop_reverse),
    ]
