# Generated by Django 5.2.11 on 2026-02-16 23:31

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscriptionfeature_planfeatureentitlement'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='base_amount_snapshot',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='discount_amount_snapshot',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='promotion_discount_type_snapshot',
            field=models.CharField(blank=True, choices=[('', '-'), ('percent', 'Percent'), ('fixed', 'Fixed')], max_length=20),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='promotion_discount_value_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='promotion_id_snapshot',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='promotion_name_snapshot',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.CreateModel(
            name='SubscriptionPlanPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('discount_type', models.CharField(choices=[('percent', 'Percent'), ('fixed', 'Fixed')], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='subscriptions.subscriptionplan')),
            ],
            options={
                'ordering': ['-priority', '-start_at', '-created_at', '-id'],
                'indexes': [models.Index(fields=['plan', 'is_active'], name='subscriptio_plan_id_cc080c_idx'), models.Index(fields=['start_at', 'end_at'], name='subscriptio_start_a_d6bbbb_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_at__gt', models.F('start_at'))), name='promo_end_after_start'), models.CheckConstraint(condition=models.Q(('discount_value__gt', 0)), name='promo_discount_value_positive'), models.CheckConstraint(condition=models.Q(('discount_type', 'fixed'), ('discount_value__lte', Decimal('100')), _connector='OR'), name='promo_percent_lte_100')],
            },
        ),
    ]
