# Generated by Django 5.2.11 on 2026-02-17 00:03

from django.db import migrations, models


def assign_default_base_tiers(apps, schema_editor):
    SubscriptionPlan = apps.get_model("subscriptions", "SubscriptionPlan")
    plans = SubscriptionPlan.objects.order_by("duration_months", "id")

    for index, plan in enumerate(plans[:3], start=1):
        plan.base_tier = index
        plan.save(update_fields=["base_tier"])


def clear_base_tiers(apps, schema_editor):
    SubscriptionPlan = apps.get_model("subscriptions", "SubscriptionPlan")
    SubscriptionPlan.objects.exclude(base_tier__isnull=True).update(base_tier=None)


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_paymenttransaction_base_amount_snapshot_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'ordering': ['base_tier', 'duration_months']},
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='base_tier',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Harga Dasar 1'), (2, 'Harga Dasar 2'), (3, 'Harga Dasar 3')], db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='duration_months',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.RunPython(assign_default_base_tiers, clear_base_tiers),
        migrations.AddConstraint(
            model_name='subscriptionplan',
            constraint=models.UniqueConstraint(condition=models.Q(('base_tier__isnull', False)), fields=('base_tier',), name='uniq_subscriptionplan_base_tier'),
        ),
    ]
