# Generated by Django 5.2.11 on 2026-02-17 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_alter_subscriptionplan_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='duration_months_snapshot',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
