# Generated by Django 5.2.4 on 2026-06-23 11:11
# A13: make the status-level default matrix (plan IS NULL) truly unique on
# PostgreSQL via NULLS NOT DISTINCT. Existing duplicate NULL-plan rows are
# deduped first so AddConstraint cannot fail on production data.

from django.db import migrations, models
from django.db.models import Count, Max


def dedupe_null_plan_entitlements(apps, schema_editor):
    PlanFeatureEntitlement = apps.get_model("subscriptions", "PlanFeatureEntitlement")
    duplicate_groups = (
        PlanFeatureEntitlement.objects.filter(plan__isnull=True)
        .values("feature_id", "subscription_status")
        .annotate(row_count=Count("id"), keep_id=Max("id"))
        .filter(row_count__gt=1)
    )
    for group in duplicate_groups:
        (
            PlanFeatureEntitlement.objects.filter(
                plan__isnull=True,
                feature_id=group["feature_id"],
                subscription_status=group["subscription_status"],
            )
            .exclude(id=group["keep_id"])
            .delete()
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_paymenttransaction_duration_months_snapshot'),
    ]

    operations = [
        migrations.RunPython(dedupe_null_plan_entitlements, noop_reverse),
        migrations.RemoveConstraint(
            model_name='planfeatureentitlement',
            name='uniq_entitlement_feature_plan_status',
        ),
        migrations.AddConstraint(
            model_name='planfeatureentitlement',
            constraint=models.UniqueConstraint(fields=('feature', 'plan', 'subscription_status'), name='uniq_entitlement_feature_plan_status', nulls_distinct=False),
        ),
    ]
