# Generated by Django 5.2.4 on 2025-08-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AHSPReferensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_ahsp', models.CharField(max_length=50)),
                ('nama_ahsp', models.TextField()),
                ('satuan', models.CharField(max_length=50)),
            ],
        ),
    ]
