# Generated by Django 5.2.4 on 2025-08-07 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referensi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ahspreferensi',
            options={'verbose_name': 'AHSP Referensi', 'verbose_name_plural': 'AHSP Referensi'},
        ),
        migrations.AddField(
            model_name='ahspreferensi',
            name='source_file',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ahspreferensi',
            name='sumber',
            field=models.CharField(default='AHSP 2025', max_length=100),
        ),
        migrations.AlterField(
            model_name='ahspreferensi',
            name='satuan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='RincianReferensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(max_length=50)),
                ('kode_item_lookup', models.CharField(max_length=50)),
                ('item', models.TextField()),
                ('satuan', models.CharField(max_length=20)),
                ('koefisien', models.DecimalField(decimal_places=6, max_digits=20)),
                ('ahsp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rincian', to='referensi.ahspreferensi')),
            ],
            options={
                'verbose_name': 'Rincian Item AHSP',
                'verbose_name_plural': 'Rincian Item AHSP',
            },
        ),
    ]
