# Generated by Django 5.2.4 on 2025-08-10 08:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referensi', '0002_alter_ahspreferensi_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ahspreferensi',
            options={'ordering': ['kode_ahsp'], 'verbose_name': 'AHSP Referensi', 'verbose_name_plural': 'AHSP Referensi'},
        ),
        migrations.AlterModelOptions(
            name='rincianreferensi',
            options={'ordering': ['ahsp_id', 'kategori', 'kode_item'], 'verbose_name': 'Rincian Item AHSP', 'verbose_name_plural': 'Rincian Item AHSP'},
        ),
        migrations.RenameField(
            model_name='rincianreferensi',
            old_name='kode_item_lookup',
            new_name='kode_item',
        ),
        migrations.RenameField(
            model_name='rincianreferensi',
            old_name='satuan',
            new_name='satuan_item',
        ),
        migrations.RenameField(
            model_name='rincianreferensi',
            old_name='item',
            new_name='uraian_item',
        ),
        migrations.AddField(
            model_name='ahspreferensi',
            name='klasifikasi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ahspreferensi',
            name='sub_klasifikasi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ahspreferensi',
            name='kode_ahsp',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='ahspreferensi',
            name='sumber',
            field=models.CharField(default='AHSP SNI 2025', max_length=100),
        ),
        migrations.AlterField(
            model_name='rincianreferensi',
            name='kategori',
            field=models.CharField(choices=[('TK', 'Tenaga Kerja'), ('BHN', 'Bahan'), ('ALT', 'Peralatan'), ('LAIN', 'Lainnya')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='rincianreferensi',
            name='koefisien',
            field=models.DecimalField(decimal_places=6, max_digits=20, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddIndex(
            model_name='ahspreferensi',
            index=models.Index(fields=['klasifikasi', 'sub_klasifikasi'], name='referensi_a_klasifi_dc9527_idx'),
        ),
        # migrations.AddConstraint(
        #     model_name='rincianreferensi',
        #     constraint=models.UniqueConstraint(fields=('ahsp', 'kategori', 'kode_item', 'uraian_item', 'satuan_item'), name='uniq_rincian_ref_per_ahsp'),
        # ),
    ]
