# Generated by Django 5.2.4 on 2025-08-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referensi', '0004_alter_rincianreferensi_kategori_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rincianreferensi',
            name='kategori',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
