# Generated by Django 5.2.4 on 2025-08-13 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referensi', '0005_sync_models_char50'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rincianreferensi',
            name='kategori',
            field=models.CharField(choices=[('TK', 'Tenaga Kerja'), ('BHN', 'Bahan'), ('ALT', 'Peralatan'), ('LAIN', 'Lainnya')], db_index=True, max_length=50),
        ),
    ]
