# Generated by Django 5.2.4 on 2025-09-15 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referensi', '0006_alter_rincianreferensi_kategori'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='rincianreferensi',
            index=models.Index(fields=['ahsp'], name='referensi_r_ahsp_id_5b62ed_idx'),
        ),
        migrations.AddIndex(
            model_name='rincianreferensi',
            index=models.Index(fields=['ahsp', 'kategori'], name='referensi_r_ahsp_id_1b09ac_idx'),
        ),
    ]
