# Generated by Django 5.2.4 on 2025-10-08 04:05

from django.db import migrations

def dedupe_ahsp_per_sumber(apps, schema_editor):
    AHSP = apps.get_model("referensi", "AHSPReferensi")
    Rincian = apps.get_model("referensi", "RincianReferensi")
    from django.db.models import Count

    dups = (
        AHSP.objects.values("sumber", "kode_ahsp")
        .annotate(c=Count("id"))
        .filter(c__gt=1)
    )
    for g in dups:
        sumber = g["sumber"]
        kode = g["kode_ahsp"]
        keep = (
            AHSP.objects
            .filter(sumber=sumber, kode_ahsp=kode)
            .order_by("id").first()
        )
        if not keep:
            continue

        (Rincian.objects
         .filter(ahsp__sumber=sumber, ahsp__kode_ahsp=kode)
         .exclude(ahsp_id=keep.id)
         .update(ahsp_id=keep.id))

        (AHSP.objects
         .filter(sumber=sumber, kode_ahsp=kode)
         .exclude(id=keep.id)
         .delete())

class Migration(migrations.Migration):

    dependencies = [
        ('referensi', '0007_rincianreferensi_referensi_r_ahsp_id_5b62ed_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(dedupe_ahsp_per_sumber, migrations.RunPython.noop),
    ]

