# Generated by Django 5.2.4 on 2025-10-08 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referensi', '0008_dedupe_ahsp_per_sumber'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ahspreferensi',
            index=models.Index(fields=['sumber', 'kode_ahsp'], name='ix_ahsp_sumber_kode'),
        ),
        migrations.AddConstraint(
            model_name='ahspreferensi',
            constraint=models.UniqueConstraint(fields=('sumber', 'kode_ahsp'), name='uniq_ahsp_per_sumber'),
        ),
    ]
