# Generated by Django 5.2.4 on 2025-11-01 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("referensi", "0009_ahsp_unique_per_sumber"),
    ]

    operations = [
        migrations.CreateModel(
            name="KodeItemReferensi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kategori",
                    models.CharField(
                        choices=[
                            ("TK", "Tenaga Kerja"),
                            ("BHN", "Bahan"),
                            ("ALT", "Peralatan"),
                            ("LAIN", "Lainnya"),
                        ],
                        max_length=50,
                    ),
                ),
                ("uraian_item", models.TextField()),
                ("satuan_item", models.CharField(max_length=20)),
                ("kode_item", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Kode Item Referensi",
                "verbose_name_plural": "Kode Item Referensi",
                "db_table": "referensi_kode_item",
                "indexes": [
                    models.Index(
                        fields=["kategori"], name="referensi_k_kategor_70ecbb_idx"
                    ),
                    models.Index(
                        fields=["kode_item"], name="referensi_k_kode_it_04662b_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("kategori", "uraian_item", "satuan_item"),
                        name="uniq_kode_item_kombinasi",
                    )
                ],
            },
        ),
    ]
