# Generated by Django 5.2.2 on 2025-11-02 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referensi', '0010_kodeitemreferensi'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ahspreferensi',
            index=models.Index(fields=['sumber'], name='ix_ahsp_sumber'),
        ),
        migrations.AddIndex(
            model_name='ahspreferensi',
            index=models.Index(fields=['klasifikasi'], name='ix_ahsp_klasifikasi'),
        ),
        migrations.AddIndex(
            model_name='ahspreferensi',
            index=models.Index(fields=['sumber', 'klasifikasi'], name='ix_ahsp_sumber_klas'),
        ),
        migrations.AddIndex(
            model_name='kodeitemreferensi',
            index=models.Index(fields=['kategori', 'uraian_item', 'satuan_item', 'kode_item'], name='ix_kodeitem_covering'),
        ),
        migrations.AddIndex(
            model_name='rincianreferensi',
            index=models.Index(fields=['kategori', 'kode_item'], name='ix_rincian_kat_kode'),
        ),
        migrations.AddIndex(
            model_name='rincianreferensi',
            index=models.Index(fields=['koefisien'], name='ix_rincian_koef'),
        ),
        migrations.AddIndex(
            model_name='rincianreferensi',
            index=models.Index(fields=['satuan_item'], name='ix_rincian_satuan'),
        ),
        migrations.AddIndex(
            model_name='rincianreferensi',
            index=models.Index(fields=['ahsp', 'kategori', 'kode_item'], name='ix_rincian_covering'),
        ),
    ]
