# Generated by Django 5.2.2 on 2025-11-02 11:26
"""
PHASE 3 DAY 2: Full-Text Search Implementation

Adds PostgreSQL full-text search capability to AHSPReferensi model:
1. Add search_vector tsvector column
2. Create GIN index for fast full-text search
3. Create trigger to auto-update search_vector on INSERT/UPDATE

Expected Impact: 80-95% faster search queries
"""

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referensi', '0011_add_performance_indexes'),
    ]

    operations = [
        # Step 1: Add search_vector column (tsvector type)
        migrations.RunSQL(
            sql="""
                ALTER TABLE referensi_ahspreferensi
                ADD COLUMN search_vector tsvector
                GENERATED ALWAYS AS (
                    setweight(to_tsvector('indonesian', coalesce(kode_ahsp, '')), 'A') ||
                    setweight(to_tsvector('indonesian', coalesce(nama_ahsp, '')), 'B') ||
                    setweight(to_tsvector('indonesian', coalesce(klasifikasi, '')), 'C') ||
                    setweight(to_tsvector('indonesian', coalesce(sub_klasifikasi, '')), 'C')
                ) STORED;
            """,
            reverse_sql="ALTER TABLE referensi_ahspreferensi DROP COLUMN search_vector;",
        ),

        # Step 2: Create GIN index on search_vector for fast full-text search
        migrations.RunSQL(
            sql="""
                CREATE INDEX ix_ahsp_search_vector
                ON referensi_ahspreferensi
                USING gin(search_vector);
            """,
            reverse_sql="DROP INDEX IF EXISTS ix_ahsp_search_vector;",
        ),
    ]
