# Generated by Django 5.2.2 on 2025-11-02 12:34
"""
PHASE 3 DAY 3: Materialized View for AHSP Statistics

Creates a materialized view that pre-computes expensive aggregations:
- Total rincian count per AHSP
- Category counts (TK, BHN, ALT, LAIN)
- Anomaly counts (zero coefficient, missing unit)

Expected Impact: 90-99% faster statistics queries
"""

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referensi', '0012_add_fulltext_search'),
    ]

    operations = [
        # Create materialized view for AHSP statistics
        migrations.RunSQL(
            sql="""
                CREATE MATERIALIZED VIEW referensi_ahsp_stats AS
                SELECT
                    ahsp.id AS ahsp_id,
                    ahsp.kode_ahsp,
                    ahsp.nama_ahsp,
                    ahsp.klasifikasi,
                    ahsp.sub_klasifikasi,
                    ahsp.satuan,
                    ahsp.sumber,
                    ahsp.source_file,

                    -- Total rincian count
                    COUNT(DISTINCT r.id) AS rincian_total,

                    -- Category counts
                    COUNT(DISTINCT r.id) FILTER (WHERE r.kategori = 'TK') AS tk_count,
                    COUNT(DISTINCT r.id) FILTER (WHERE r.kategori = 'BHN') AS bhn_count,
                    COUNT(DISTINCT r.id) FILTER (WHERE r.kategori = 'ALT') AS alt_count,
                    COUNT(DISTINCT r.id) FILTER (WHERE r.kategori = 'LAIN') AS lain_count,

                    -- Anomaly counts
                    COUNT(DISTINCT r.id) FILTER (WHERE r.koefisien = 0) AS zero_coef_count,
                    COUNT(DISTINCT r.id) FILTER (WHERE r.satuan_item IS NULL OR r.satuan_item = '') AS missing_unit_count

                FROM referensi_ahspreferensi ahsp
                LEFT JOIN referensi_rincianreferensi r ON r.ahsp_id = ahsp.id
                GROUP BY
                    ahsp.id,
                    ahsp.kode_ahsp,
                    ahsp.nama_ahsp,
                    ahsp.klasifikasi,
                    ahsp.sub_klasifikasi,
                    ahsp.satuan,
                    ahsp.sumber,
                    ahsp.source_file;
            """,
            reverse_sql="DROP MATERIALIZED VIEW IF EXISTS referensi_ahsp_stats;",
        ),

        # Create unique index on ahsp_id for fast lookups
        migrations.RunSQL(
            sql="""
                CREATE UNIQUE INDEX idx_ahsp_stats_ahsp_id
                ON referensi_ahsp_stats (ahsp_id);
            """,
            reverse_sql="DROP INDEX IF EXISTS idx_ahsp_stats_ahsp_id;",
        ),

        # Create index on sumber for filtering
        migrations.RunSQL(
            sql="""
                CREATE INDEX idx_ahsp_stats_sumber
                ON referensi_ahsp_stats (sumber);
            """,
            reverse_sql="DROP INDEX IF EXISTS idx_ahsp_stats_sumber;",
        ),

        # Create index on klasifikasi for filtering
        migrations.RunSQL(
            sql="""
                CREATE INDEX idx_ahsp_stats_klasifikasi
                ON referensi_ahsp_stats (klasifikasi);
            """,
            reverse_sql="DROP INDEX IF EXISTS idx_ahsp_stats_klasifikasi;",
        ),

        # Create index on kode_ahsp for fast lookup
        migrations.RunSQL(
            sql="""
                CREATE INDEX idx_ahsp_stats_kode_ahsp
                ON referensi_ahsp_stats (kode_ahsp);
            """,
            reverse_sql="DROP INDEX IF EXISTS idx_ahsp_stats_kode_ahsp;",
        ),
    ]
