# Generated by Django 5.2.4 on 2025-11-02 13:36

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referensi', '0013_add_materialized_view_stats'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ahspreferensi',
            options={'ordering': ['kode_ahsp'], 'permissions': [('view_ahsp_stats', 'Can view AHSP statistics'), ('import_ahsp_data', 'Can import AHSP data'), ('export_ahsp_data', 'Can export AHSP data')], 'verbose_name': 'AHSP Referensi', 'verbose_name_plural': 'AHSP Referensi'},
        ),
        migrations.CreateModel(
            name='HistoricalAHSPReferensi',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('kode_ahsp', models.CharField(db_index=True, max_length=50)),
                ('nama_ahsp', models.TextField()),
                ('klasifikasi', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_klasifikasi', models.CharField(blank=True, max_length=100, null=True)),
                ('satuan', models.CharField(blank=True, max_length=50, null=True)),
                ('sumber', models.CharField(default='AHSP SNI 2025', max_length=100)),
                ('source_file', models.CharField(blank=True, max_length=100, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical AHSP Referensi',
                'verbose_name_plural': 'historical AHSP Referensi',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalKodeItemReferensi',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('kategori', models.CharField(choices=[('TK', 'Tenaga Kerja'), ('BHN', 'Bahan'), ('ALT', 'Peralatan'), ('LAIN', 'Lainnya')], max_length=50)),
                ('uraian_item', models.TextField()),
                ('satuan_item', models.CharField(max_length=20)),
                ('kode_item', models.CharField(max_length=50)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Kode Item Referensi',
                'verbose_name_plural': 'historical Kode Item Referensi',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRincianReferensi',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('kategori', models.CharField(choices=[('TK', 'Tenaga Kerja'), ('BHN', 'Bahan'), ('ALT', 'Peralatan'), ('LAIN', 'Lainnya')], db_index=True, max_length=50)),
                ('kode_item', models.CharField(max_length=50)),
                ('uraian_item', models.TextField()),
                ('satuan_item', models.CharField(max_length=20)),
                ('koefisien', models.DecimalField(decimal_places=6, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('ahsp', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='referensi.ahspreferensi')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Rincian Item AHSP',
                'verbose_name_plural': 'historical Rincian Item AHSP',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
