# Generated by Django 5.2.4 on 2025-11-02 13:36

from django.db import migrations


def create_permission_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    ContentType = apps.get_model('contenttypes', 'ContentType')
    ahsp_ct, _ = ContentType.objects.get_or_create(
        app_label='referensi',
        model='ahspreferensi',
    )
    rincian_ct, _ = ContentType.objects.get_or_create(
        app_label='referensi',
        model='rincianreferensi',
    )
    kodeitem_ct, _ = ContentType.objects.get_or_create(
        app_label='referensi',
        model='kodeitemreferensi',
    )

    required_permissions = {
        'view_ahspreferensi': ("Can view AHSP Referensi", ahsp_ct),
        'add_ahspreferensi': ("Can add AHSP Referensi", ahsp_ct),
        'change_ahspreferensi': ("Can change AHSP Referensi", ahsp_ct),
        'delete_ahspreferensi': ("Can delete AHSP Referensi", ahsp_ct),
        'view_rincianreferensi': ("Can view Rincian Referensi", rincian_ct),
        'add_rincianreferensi': ("Can add Rincian Referensi", rincian_ct),
        'change_rincianreferensi': ("Can change Rincian Referensi", rincian_ct),
        'delete_rincianreferensi': ("Can delete Rincian Referensi", rincian_ct),
        'view_kodeitemreferensi': ("Can view Kode Item Referensi", kodeitem_ct),
        'add_kodeitemreferensi': ("Can add Kode Item Referensi", kodeitem_ct),
        'change_kodeitemreferensi': ("Can change Kode Item Referensi", kodeitem_ct),
        'delete_kodeitemreferensi': ("Can delete Kode Item Referensi", kodeitem_ct),
        'view_ahsp_stats': ("Can view AHSP statistics", ahsp_ct),
        'import_ahsp_data': ("Can import AHSP data", ahsp_ct),
        'export_ahsp_data': ("Can export AHSP data", ahsp_ct),
    }

    permissions = {}
    for codename, (name, content_type) in required_permissions.items():
        permission, _ = Permission.objects.get_or_create(
            codename=codename,
            content_type=content_type,
            defaults={'name': name},
        )
        permissions[codename] = permission

    custom_defaults = {
        'view_ahsp_stats': "Can view AHSP statistics",
        'import_ahsp_data': "Can import AHSP data",
        'export_ahsp_data': "Can export AHSP data",
    }
    for codename, name in custom_defaults.items():
        if codename not in permissions:
            permission, _ = Permission.objects.get_or_create(
                codename=codename,
                content_type=ahsp_ct,
                defaults={'name': name},
            )
            permissions[codename] = permission

    def get_perms(codenames):
        return [permissions[code] for code in codenames]

    viewer_codes = [
        'view_ahspreferensi',
        'view_rincianreferensi',
        'view_kodeitemreferensi',
        'view_ahsp_stats',
    ]
    editor_codes = viewer_codes + [
        'change_ahspreferensi',
        'change_rincianreferensi',
        'change_kodeitemreferensi',
        'import_ahsp_data',
    ]
    admin_codes = editor_codes + [
        'add_ahspreferensi',
        'add_rincianreferensi',
        'add_kodeitemreferensi',
        'delete_ahspreferensi',
        'delete_rincianreferensi',
        'delete_kodeitemreferensi',
        'export_ahsp_data',
    ]

    assignments = (
        ('Referensi Viewer', viewer_codes),
        ('Referensi Editor', editor_codes),
        ('Referensi Admin', admin_codes),
    )

    for name, codename_list in assignments:
        group, _ = Group.objects.get_or_create(name=name)
        group.permissions.set(get_perms(codename_list))


def remove_permission_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name__in=[
        'Referensi Viewer',
        'Referensi Editor',
        'Referensi Admin',
    ]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('referensi', '0014_ahspstats_alter_ahspreferensi_options_and_more'),
    ]

    operations = [
        migrations.RunPython(
            create_permission_groups,
            remove_permission_groups,
        ),
    ]
