# Generated by Django 5.2.4 on 2025-11-02 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referensi', '0015_create_permission_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='AHSPStats',
            fields=[
                ('ahsp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('kode_ahsp', models.CharField(max_length=50)),
                ('nama_ahsp', models.TextField()),
                ('klasifikasi', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_klasifikasi', models.CharField(blank=True, max_length=100, null=True)),
                ('satuan', models.CharField(blank=True, max_length=50, null=True)),
                ('sumber', models.CharField(max_length=100)),
                ('source_file', models.CharField(blank=True, max_length=100, null=True)),
                ('rincian_total', models.IntegerField()),
                ('tk_count', models.IntegerField()),
                ('bhn_count', models.IntegerField()),
                ('alt_count', models.IntegerField()),
                ('lain_count', models.IntegerField()),
                ('zero_coef_count', models.IntegerField()),
                ('missing_unit_count', models.IntegerField()),
            ],
            options={
                'verbose_name': 'AHSP Statistics (Materialized View)',
                'verbose_name_plural': 'AHSP Statistics (Materialized View)',
                'db_table': 'referensi_ahsp_stats',
                'managed': False,
            },
        ),
    ]
