# Generated by Django 5.2.2 on 2025-11-04 08:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referensi', '0016_ahspstats'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], db_index=True, max_length=20)),
                ('period_start', models.DateTimeField(db_index=True, help_text='Start of the aggregation period')),
                ('period_end', models.DateTimeField(help_text='End of the aggregation period')),
                ('category', models.CharField(choices=[('file_upload', 'File Upload'), ('rate_limit', 'Rate Limit'), ('xss', 'XSS Protection'), ('authentication', 'Authentication'), ('import', 'Import Operation'), ('export', 'Export Operation'), ('data_change', 'Data Change'), ('permission', 'Permission'), ('system', 'System')], db_index=True, max_length=50)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], db_index=True, max_length=20)),
                ('event_count', models.IntegerField(default=0, help_text='Total events in this period')),
                ('unique_users', models.IntegerField(default=0, help_text='Number of unique users')),
                ('unique_ips', models.IntegerField(default=0, help_text='Number of unique IP addresses')),
                ('top_events', models.JSONField(blank=True, default=list, help_text='List of most common event types with counts')),
                ('top_users', models.JSONField(blank=True, default=list, help_text='List of most active users with counts')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Audit Log Summary',
                'verbose_name_plural': 'Audit Log Summaries',
                'db_table': 'referensi_audit_log_summary',
                'ordering': ['-period_start'],
                'indexes': [models.Index(fields=['period_type', '-period_start'], name='referensi_a_period__f78b06_idx'), models.Index(fields=['category', '-period_start'], name='referensi_a_categor_8a7537_idx')],
                'unique_together': {('period_type', 'period_start', 'category', 'severity')},
            },
        ),
        migrations.CreateModel(
            name='SecurityAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When the event occurred')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], db_index=True, default='info', help_text='Severity level of the event', max_length=20)),
                ('category', models.CharField(choices=[('file_upload', 'File Upload'), ('rate_limit', 'Rate Limit'), ('xss', 'XSS Protection'), ('authentication', 'Authentication'), ('import', 'Import Operation'), ('export', 'Export Operation'), ('data_change', 'Data Change'), ('permission', 'Permission'), ('system', 'System')], db_index=True, help_text='Category of the security event', max_length=50)),
                ('username', models.CharField(blank=True, db_index=True, help_text='Username snapshot (preserved even if user deleted)', max_length=150)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, help_text='IP address of the request', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string from the request')),
                ('event_type', models.CharField(db_index=True, help_text="Specific event type (e.g., 'file_too_large', 'rate_limit_exceeded')", max_length=100)),
                ('message', models.TextField(help_text='Human-readable description of the event')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional event-specific data (JSON)')),
                ('path', models.CharField(blank=True, db_index=True, help_text='Request path that triggered the event', max_length=500)),
                ('method', models.CharField(blank=True, help_text='HTTP method (GET, POST, etc.)', max_length=10)),
                ('resolved', models.BooleanField(db_index=True, default=False, help_text='Whether this event has been reviewed/resolved')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When the event was marked as resolved', null=True)),
                ('notes', models.TextField(blank=True, help_text='Admin notes about this event')),
                ('resolved_by', models.ForeignKey(blank=True, help_text='User who resolved the event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, help_text='User who triggered the event (if authenticated)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Security Audit Log',
                'verbose_name_plural': 'Security Audit Logs',
                'db_table': 'referensi_security_audit_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'severity'], name='referensi_s_timesta_824f40_idx'), models.Index(fields=['-timestamp', 'category'], name='referensi_s_timesta_616fe1_idx'), models.Index(fields=['user', '-timestamp'], name='referensi_s_user_id_0bd629_idx'), models.Index(fields=['ip_address', '-timestamp'], name='referensi_s_ip_addr_1a0870_idx'), models.Index(fields=['event_type', '-timestamp'], name='referensi_s_event_t_f9eb8e_idx'), models.Index(fields=['resolved', '-timestamp'], name='referensi_s_resolve_0f8e47_idx')],
            },
        ),
    ]
