# Generated by Django 5.2.4 on 2026-01-17 02:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referensi', '0019_enable_pg_trgm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AHSPImportStaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.CharField(max_length=255)),
                ('parent_ahsp_code', models.CharField(blank=True, help_text='Kode AHSP Induk (misal A.2.2.1)', max_length=50, null=True)),
                ('segment_type', models.CharField(blank=True, choices=[('A', 'A. Tenaga Kerja'), ('B', 'B. Bahan'), ('C', 'C. Peralatan'), ('HEADING', 'Heading / Judul Bab')], max_length=20, null=True)),
                ('kode_item', models.CharField(help_text='Kode Item (misal L.01 atau batu_kali)', max_length=50)),
                ('uraian_item', models.TextField(help_text="Nama Item (misal 'Pekerja' atau 'Semen')")),
                ('satuan_item', models.CharField(blank=True, max_length=50, null=True)),
                ('koefisien', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('is_valid', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staging Import AHSP',
                'verbose_name_plural': 'Staging Import AHSP',
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
