# Generated by Django 5.2.4 on 2026-06-02 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referensi', '0020_ahspimportstaging'),
    ]

    operations = [
        migrations.AddField(
            model_name='ahspimportstaging',
            name='sumber',
            field=models.CharField(blank=True, default='', help_text="Versi/tahun sumber AHSP, mis. 'AHSP 2024'", max_length=100),
        ),
    ]
