# Generated by Django 5.2.11 on 2026-06-02 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referensi', '0021_ahspimportstaging_sumber'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AHSPImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('sumber', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('STAGED', 'Staged'), ('COMMITTED', 'Committed'), ('CLEARED', 'Cleared'), ('FAILED', 'Failed')], default='STAGED', max_length=20)),
                ('commit_mode', models.CharField(blank=True, choices=[('abort_duplicate', 'Abort jika duplikat'), ('merge', 'Merge/update'), ('replace', 'Replace kode dalam batch')], default='', max_length=30)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Batch Import AHSP',
                'verbose_name_plural': 'Batch Import AHSP',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='ahspimportstaging',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rows', to='referensi.ahspimportbatch'),
        ),
        migrations.AddIndex(
            model_name='ahspimportstaging',
            index=models.Index(fields=['user', 'batch'], name='ix_staging_user_batch'),
        ),
        migrations.AddIndex(
            model_name='ahspimportstaging',
            index=models.Index(fields=['user', 'file_name'], name='ix_staging_user_file'),
        ),
        migrations.AddIndex(
            model_name='ahspimportbatch',
            index=models.Index(fields=['user', 'status'], name='ix_importbatch_user_status'),
        ),
        migrations.AddIndex(
            model_name='ahspimportbatch',
            index=models.Index(fields=['sumber', 'status'], name='ix_importbatch_sumber_status'),
        ),
    ]
