# Generated by Django 5.2.4 on 2026-06-08 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referensi', '0023_unique_registry_code_per_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ahspimportstaging',
            name='segment_type',
            field=models.CharField(blank=True, choices=[('A', 'A. Tenaga Kerja'), ('B', 'B. Bahan'), ('C', 'C. Peralatan'), ('LAIN', 'Lainnya'), ('HEADING', 'Heading / Judul Bab')], max_length=20, null=True),
        ),
    ]
