# Generated by Django 5.2.4 on 2025-08-13 09:13

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0006_alter_project_anggaran_owner_and_more'),
        ('referensi', '0006_alter_rincianreferensi_kategori'),
    ]

    operations = [
        migrations.CreateModel(
            name='HargaItemProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kode_item', models.CharField(max_length=100)),
                ('satuan', models.CharField(blank=True, max_length=50, null=True)),
                ('uraian', models.TextField()),
                ('kategori', models.CharField(choices=[('TK', 'Tenaga Kerja'), ('BHN', 'Bahan'), ('ALT', 'Alat'), ('LAIN', 'Lain-lain')], max_length=10)),
                ('harga_satuan', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harga_items', to='dashboard.project')),
            ],
        ),
        migrations.CreateModel(
            name='Klasifikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('ordering_index', models.PositiveIntegerField(db_index=True, default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='klasifikasi_list', to='dashboard.project')),
            ],
            options={
                'ordering': ['ordering_index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Pekerjaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(choices=[('ref', 'Referensi'), ('custom', 'Custom'), ('ref_modified', 'Ref Modified')], max_length=20)),
                ('snapshot_kode', models.CharField(blank=True, max_length=100, null=True)),
                ('snapshot_uraian', models.TextField(blank=True, null=True)),
                ('snapshot_satuan', models.CharField(blank=True, max_length=50, null=True)),
                ('auto_load_rincian', models.BooleanField(default=True)),
                ('detail_ready', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('ordering_index', models.PositiveIntegerField(db_index=True, default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pekerjaan_list', to='dashboard.project')),
                ('ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='referensi.ahspreferensi')),
            ],
            options={
                'ordering': ['ordering_index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DetailAHSPProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kategori', models.CharField(choices=[('TK', 'Tenaga Kerja'), ('BHN', 'Bahan'), ('ALT', 'Alat'), ('LAIN', 'Lain-lain')], max_length=10)),
                ('kode', models.CharField(max_length=100)),
                ('uraian', models.TextField()),
                ('satuan', models.CharField(blank=True, max_length=50, null=True)),
                ('koefisien', models.DecimalField(decimal_places=6, max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_ahsp', to='dashboard.project')),
                ('harga_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detail_refs', to='detail_project.hargaitemproject')),
                ('pekerjaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_list', to='detail_project.pekerjaan')),
            ],
        ),
        migrations.CreateModel(
            name='SubKlasifikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('ordering_index', models.PositiveIntegerField(db_index=True, default=0)),
                ('klasifikasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_list', to='detail_project.klasifikasi')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subklasifikasi_list', to='dashboard.project')),
            ],
            options={
                'ordering': ['ordering_index', 'id'],
            },
        ),
        migrations.AddField(
            model_name='pekerjaan',
            name='sub_klasifikasi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pekerjaan_list', to='detail_project.subklasifikasi'),
        ),
        migrations.CreateModel(
            name='VolumePekerjaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('pekerjaan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='volume', to='detail_project.pekerjaan')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volume_list', to='dashboard.project')),
            ],
        ),
        migrations.AddIndex(
            model_name='hargaitemproject',
            index=models.Index(fields=['project', 'kategori'], name='detail_proj_project_dbaa1d_idx'),
        ),
        migrations.AddConstraint(
            model_name='hargaitemproject',
            constraint=models.UniqueConstraint(fields=('project', 'kode_item'), name='uniq_harga_kode_per_project'),
        ),
        migrations.AlterUniqueTogether(
            name='klasifikasi',
            unique_together={('project', 'ordering_index')},
        ),
        migrations.AddIndex(
            model_name='detailahspproject',
            index=models.Index(fields=['project', 'pekerjaan'], name='detail_proj_project_7b2d66_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='detailahspproject',
            unique_together={('project', 'pekerjaan', 'kode')},
        ),
        migrations.AlterUniqueTogether(
            name='subklasifikasi',
            unique_together={('project', 'klasifikasi', 'ordering_index')},
        ),
        migrations.AlterUniqueTogether(
            name='pekerjaan',
            unique_together={('project', 'ordering_index')},
        ),
        migrations.AlterUniqueTogether(
            name='volumepekerjaan',
            unique_together={('project', 'pekerjaan')},
        ),
    ]
