# Generated by Django 5.2.4 on 2025-09-10 03:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_project_anggaran_owner_and_more'),
        ('detail_project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolumeFormulaState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw', models.TextField(blank=True, default='')),
                ('is_fx', models.BooleanField(default=True)),
                ('pekerjaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formula_state', to='detail_project.pekerjaan')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volume_formula_states', to='dashboard.project')),
            ],
            options={
                'indexes': [models.Index(fields=['project', 'pekerjaan'], name='detail_proj_project_d619ff_idx')],
                'constraints': [models.UniqueConstraint(fields=('project', 'pekerjaan'), name='uniq_formula_per_project_pekerjaan')],
            },
        ),
    ]
