# Generated by Django 5.2.4 on 2025-09-15 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_project_anggaran_owner_and_more'),
        ('detail_project', '0002_volumeformulastate'),
        ('referensi', '0007_rincianreferensi_referensi_r_ahsp_id_5b62ed_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailahspproject',
            name='ref_ahsp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detail_bundles', to='referensi.ahspreferensi'),
        ),
        migrations.AddIndex(
            model_name='detailahspproject',
            index=models.Index(fields=['project', 'pekerjaan', 'kategori'], name='detail_proj_project_93d725_idx'),
        ),
        migrations.AddConstraint(
            model_name='detailahspproject',
            constraint=models.CheckConstraint(condition=models.Q(('ref_ahsp__isnull', True), ('kategori', 'LAIN'), _connector='OR'), name='ref_ahsp_only_for_lain'),
        ),
    ]
