# Generated by Django 5.2.4 on 2025-09-16 09:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_project_anggaran_owner_and_more'),
        ('detail_project', '0003_detailahspproject_ref_ahsp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('markup_percent', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='dashboard.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
