# Generated by Django 5.2.4 on 2025-09-17 04:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail_project', '0004_projectpricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='pekerjaan',
            name='markup_override_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Override % BUK khusus pekerjaan ini; null=pakai default project', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
