# Generated by Django 5.2.4 on 2025-09-19 07:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_project_anggaran_owner_and_more'),
        ('detail_project', '0005_pekerjaan_markup_override_percent'),
        ('referensi', '0007_rincianreferensi_referensi_r_ahsp_id_5b62ed_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpricing',
            name='ppn_percent',
            field=models.DecimalField(decimal_places=2, default=11, help_text='PPN (%) yang diterapkan pada Rekap RAB', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='projectpricing',
            name='rounding_base',
            field=models.PositiveIntegerField(default=10000, help_text='Basis pembulatan grand total (Rp), mis. 10000'),
        ),
        migrations.AddIndex(
            model_name='detailahspproject',
            index=models.Index(fields=['project', 'kategori', 'harga_item'], name='detail_proj_project_82fd5e_idx'),
        ),
    ]
