# Generated by Django 5.2.4 on 2025-09-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail_project', '0006_projectpricing_ppn_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpricing',
            name='ppn_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='projectpricing',
            name='rounding_base',
            field=models.PositiveIntegerField(default=10000),
        ),
    ]
