# Generated by Django 5.2.4 on 2025-09-19 12:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_project_anggaran_owner_and_more'),
        ('detail_project', '0007_alter_projectpricing_ppn_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpricing',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='projectpricing',
            name='markup_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=6),
        ),
        migrations.AlterField(
            model_name='projectpricing',
            name='ppn_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('11.00'), max_digits=6),
        ),
        migrations.AddConstraint(
            model_name='projectpricing',
            constraint=models.UniqueConstraint(fields=('project',), name='uniq_project_pricing_one'),
        ),
    ]
