# Generated by Django 5.2.4 on 2025-09-20 03:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail_project', '0008_alter_projectpricing_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpricing',
            name='ppn_percent',
            field=models.DecimalField(decimal_places=2, default=11, help_text='PPN (%) yang diterapkan pada Rekap RAB', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='projectpricing',
            name='rounding_base',
            field=models.PositiveIntegerField(default=10000, help_text='Basis pembulatan grand total (Rp), mis. 10000'),
        ),
    ]
