# Generated by Django 5.2.4 on 2025-10-21 06:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail_project', '0009_alter_projectpricing_ppn_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pekerjaan',
            name='markup_override_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Override % Profit/Margin khusus pekerjaan ini; null=pakai default project', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
