# Generated by Django 5.2.4 on 2025-10-22 04:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_project_anggaran_owner_and_more'),
        ('detail_project', '0010_alter_pekerjaan_markup_override_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='TahapPelaksanaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(help_text='Nama tahapan (contoh: Tahap 1 - Persiapan)', max_length=200)),
                ('urutan', models.IntegerField(default=0, help_text='Urutan tahapan (untuk sorting)')),
                ('deskripsi', models.TextField(blank=True, help_text='Deskripsi detail tahapan (opsional)')),
                ('tanggal_mulai', models.DateField(blank=True, help_text='Tanggal rencana mulai (opsional)', null=True)),
                ('tanggal_selesai', models.DateField(blank=True, help_text='Tanggal rencana selesai (opsional)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tahapan', to='dashboard.project')),
            ],
            options={
                'verbose_name': 'Tahap Pelaksanaan',
                'verbose_name_plural': 'Tahap Pelaksanaan',
                'ordering': ['urutan', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PekerjaanTahapan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proporsi_volume', models.DecimalField(decimal_places=2, help_text='Proporsi volume (%) untuk tahap ini. Range: 0.01 - 100.00', max_digits=5, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(100.0)])),
                ('catatan', models.TextField(blank=True, help_text='Catatan split volume (opsional)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pekerjaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tahapan_assignments', to='detail_project.pekerjaan')),
                ('tahapan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pekerjaan_items', to='detail_project.tahappelaksanaan')),
            ],
            options={
                'verbose_name': 'Assignment Pekerjaan ke Tahapan',
                'verbose_name_plural': 'Assignment Pekerjaan ke Tahapan',
                'ordering': ['tahapan__urutan', 'pekerjaan__ordering_index'],
            },
        ),
        migrations.AddIndex(
            model_name='tahappelaksanaan',
            index=models.Index(fields=['project', 'urutan'], name='detail_proj_project_63ccc9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tahappelaksanaan',
            unique_together={('project', 'nama')},
        ),
        migrations.AddIndex(
            model_name='pekerjaantahapan',
            index=models.Index(fields=['pekerjaan', 'tahapan'], name='detail_proj_pekerja_1f721e_idx'),
        ),
        migrations.AddIndex(
            model_name='pekerjaantahapan',
            index=models.Index(fields=['tahapan'], name='detail_proj_tahapan_c75a65_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pekerjaantahapan',
            unique_together={('pekerjaan', 'tahapan')},
        ),
    ]
