# Generated by Django 5.2.4 on 2025-11-01 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detail_project', '0013_add_weekly_canonical_storage'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pekerjaanprogressweekly',
            new_name='detail_proj_pekerja_27e8a7_idx',
            old_name='detail_proj_pekerjaan_week_idx',
        ),
        migrations.RenameIndex(
            model_name='pekerjaanprogressweekly',
            new_name='detail_proj_project_863379_idx',
            old_name='detail_proj_project_week_idx',
        ),
        migrations.RenameIndex(
            model_name='pekerjaanprogressweekly',
            new_name='detail_proj_week_st_3d5bed_idx',
            old_name='detail_proj_week_dates_idx',
        ),
    ]
