# Generated by Django 5.2.4 on 2025-11-06 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detail_project', '0015_projectparameter'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='projectparameter',
            new_name='detail_proj_project_541dd2_idx',
            old_name='detail_proj_project_6c8b4e_idx',
        ),
    ]
