# Generated by Django 5.2.4 on 2025-11-09 07:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0009_remove_tanggal_mulai_default"),
        ("detail_project", "0017_add_ref_pekerjaan_bundle_support"),
        ("referensi", "0019_enable_pg_trgm"),
    ]

    operations = [
        migrations.CreateModel(
            name="DetailAHSPExpanded",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kategori",
                    models.CharField(
                        choices=[
                            ("TK", "Tenaga Kerja"),
                            ("BHN", "Bahan"),
                            ("ALT", "Alat"),
                            ("LAIN", "Lain-lain"),
                        ],
                        max_length=10,
                    ),
                ),
                ("kode", models.CharField(max_length=100)),
                ("uraian", models.TextField()),
                ("satuan", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "koefisien",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Koefisien final setelah expansion (sudah dikali multiplier)",
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "source_bundle_kode",
                    models.CharField(
                        blank=True,
                        help_text="Kode bundle LAIN yang di-expand (NULL jika direct input)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "expansion_depth",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Kedalaman expansion (0=direct, 1=1-level bundle, 2=nested, dst)",
                    ),
                ),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="detailahspproject",
            name="bundle_ref_only_for_lain",
        ),
        migrations.AlterField(
            model_name="detailahspproject",
            name="ref_ahsp",
            field=models.ForeignKey(
                blank=True,
                help_text="Reference to AHSP master (bundle support for LAIN category)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="detail_bundles",
                to="referensi.ahspreferensi",
            ),
        ),
        migrations.AlterField(
            model_name="detailahspproject",
            name="ref_pekerjaan",
            field=models.ForeignKey(
                blank=True,
                help_text="Reference to another Pekerjaan in same project (bundle support for LAIN category)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bundle_references",
                to="detail_project.pekerjaan",
            ),
        ),
        migrations.AddConstraint(
            model_name="detailahspproject",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("ref_ahsp__isnull", True), ("ref_pekerjaan__isnull", True)
                    ),
                    ("kategori", "LAIN"),
                    _connector="OR",
                ),
                name="bundle_ref_only_for_lain",
            ),
        ),
        migrations.AddField(
            model_name="detailahspexpanded",
            name="harga_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="expanded_refs",
                to="detail_project.hargaitemproject",
            ),
        ),
        migrations.AddField(
            model_name="detailahspexpanded",
            name="pekerjaan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detail_expanded_list",
                to="detail_project.pekerjaan",
            ),
        ),
        migrations.AddField(
            model_name="detailahspexpanded",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detail_ahsp_expanded",
                to="dashboard.project",
            ),
        ),
        migrations.AddField(
            model_name="detailahspexpanded",
            name="source_detail",
            field=models.ForeignKey(
                help_text="Source raw input dari DetailAHSPProject",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expanded_components",
                to="detail_project.detailahspproject",
            ),
        ),
        migrations.AddIndex(
            model_name="detailahspexpanded",
            index=models.Index(
                fields=["project", "pekerjaan"], name="detail_proj_project_e7819d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="detailahspexpanded",
            index=models.Index(
                fields=["project", "pekerjaan", "kategori"],
                name="detail_proj_project_12203a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="detailahspexpanded",
            index=models.Index(
                fields=["source_detail"], name="detail_proj_source__3ec04f_idx"
            ),
        ),
    ]
