# Generated by Django 5.2.4 on 2025-11-14 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detail_project', '0019_detailahsptaudit'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='detailahspaudit',
            new_name='detail_proj_project_0b77d8_idx',
            old_name='audit_project_created_idx',
        ),
        migrations.RenameIndex(
            model_name='detailahspaudit',
            new_name='detail_proj_pekerja_57bcbf_idx',
            old_name='audit_pekerjaan_created_idx',
        ),
        migrations.RenameIndex(
            model_name='detailahspaudit',
            new_name='detail_proj_action_dd72f4_idx',
            old_name='audit_action_idx',
        ),
    ]
