# Generated by Django 5.2.2 on 2025-11-14 03:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_remove_tanggal_mulai_default'),
        ('detail_project', '0020_rename_audit_project_created_idx_detail_proj_project_0b77d8_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pekerjaan',
            name='detail_last_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ProjectChangeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_ahsp_change', models.DateTimeField(blank=True, null=True)),
                ('last_harga_change', models.DateTimeField(blank=True, null=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='change_status', to='dashboard.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
