# Generated by Django 5.2.2 on 2025-12-02 21:35

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Phase 1 Performance Optimization - Add database indexes
    for Rekap Kebutuhan query performance improvement.

    Expected improvement: 20-30% faster queries
    """

    dependencies = [
        ('detail_project', '0026_add_evm_cost_fields'),
    ]

    operations = [
        # Index for main Rekap Kebutuhan query filter
        migrations.AddIndex(
            model_name='detailahspexpanded',
            index=models.Index(
                fields=['project', 'pekerjaan_id'],
                name='idx_dahsp_proj_pek'
            ),
        ),
        # Index for kategori/kode sorting and filtering
        migrations.AddIndex(
            model_name='detailahspexpanded',
            index=models.Index(
                fields=['kategori', 'kode'],
                name='idx_dahsp_kat_kode'
            ),
        ),
        # Index for VolumePekerjaan lookup
        migrations.AddIndex(
            model_name='volumepekerjaan',
            index=models.Index(
                fields=['project', 'pekerjaan_id'],
                name='idx_volpek_proj_pek'
            ),
        ),
        # Index for Pekerjaan filtering by sub_klasifikasi
        migrations.AddIndex(
            model_name='pekerjaan',
            index=models.Index(
                fields=['project', 'sub_klasifikasi'],
                name='idx_pek_proj_sub'
            ),
        ),
    ]
