# Generated by Django 5.2.4 on 2025-12-03 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detail_project', '0027_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='detailahspexpanded',
            name='idx_dahsp_proj_pek',
        ),
        migrations.RemoveIndex(
            model_name='detailahspexpanded',
            name='idx_dahsp_kat_kode',
        ),
        migrations.RemoveIndex(
            model_name='pekerjaan',
            name='idx_pek_proj_sub',
        ),
        migrations.RemoveIndex(
            model_name='volumepekerjaan',
            name='idx_volpek_proj_pek',
        ),
    ]
