# Generated by Django 5.2.2 on 2025-12-16 08:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail_project', '0028_remove_detailahspexpanded_idx_dahsp_proj_pek_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportSession',
            fields=[
                ('export_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique export session ID', primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('rekap', 'Laporan Rekap'), ('monthly', 'Laporan Bulanan'), ('weekly', 'Laporan Mingguan')], help_text='Type of report to generate', max_length=20)),
                ('format_type', models.CharField(choices=[('pdf', 'PDF'), ('word', 'Word Document')], help_text='Output format (PDF or Word)', max_length=10)),
                ('status', models.CharField(choices=[('init', 'Initialized'), ('uploading', 'Uploading Pages'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Expired')], db_index=True, default='init', help_text='Current status of export', max_length=20)),
                ('estimated_pages', models.PositiveIntegerField(default=0, help_text='Estimated total pages')),
                ('pages_received', models.PositiveIntegerField(default=0, help_text='Number of pages uploaded')),
                ('batches_received', models.PositiveIntegerField(default=0, help_text='Number of batches uploaded')),
                ('project_name', models.CharField(blank=True, help_text='Project name for the export', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata (month, week, options, etc.)')),
                ('output_file', models.FileField(blank=True, help_text='Generated output file (PDF or Word)', null=True, upload_to='exports/%Y/%m/%d/')),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if export failed')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the export was initiated')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('expires_at', models.DateTimeField(db_index=True, help_text='When the session expires (auto-cleanup)')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the export was completed', null=True)),
                ('user', models.ForeignKey(help_text='User who initiated the export', on_delete=django.db.models.deletion.CASCADE, related_name='export_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Export Session',
                'verbose_name_plural': 'Export Sessions',
                'db_table': 'detail_project_export_session',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExportPage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('page_number', models.PositiveIntegerField(help_text='Page number (1-indexed)')),
                ('batch_index', models.PositiveIntegerField(default=0, help_text='Batch index (for tracking upload order)')),
                ('title', models.CharField(help_text="Page title (e.g., 'Gantt W1-W12', 'Kurva S Weekly')", max_length=255)),
                ('image_data', models.TextField(help_text='Base64-encoded PNG image (data:image/png;base64,...)')),
                ('format', models.CharField(default='png', help_text="Image format (usually 'png')", max_length=10)),
                ('width', models.PositiveIntegerField(blank=True, help_text='Image width in pixels', null=True)),
                ('height', models.PositiveIntegerField(blank=True, help_text='Image height in pixels', null=True)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='Image size in bytes (base64)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the page was uploaded')),
                ('session', models.ForeignKey(help_text='Parent export session', on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='detail_project.exportsession')),
            ],
            options={
                'verbose_name': 'Export Page',
                'verbose_name_plural': 'Export Pages',
                'db_table': 'detail_project_export_page',
                'ordering': ['session', 'page_number'],
            },
        ),
        migrations.AddIndex(
            model_name='exportsession',
            index=models.Index(fields=['user', '-created_at'], name='detail_proj_user_id_9f5017_idx'),
        ),
        migrations.AddIndex(
            model_name='exportsession',
            index=models.Index(fields=['status', 'expires_at'], name='detail_proj_status_200342_idx'),
        ),
        migrations.AddIndex(
            model_name='exportpage',
            index=models.Index(fields=['session', 'page_number'], name='detail_proj_session_b34765_idx'),
        ),
        migrations.AddIndex(
            model_name='exportpage',
            index=models.Index(fields=['session', 'batch_index'], name='detail_proj_session_cea070_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='exportpage',
            unique_together={('session', 'page_number')},
        ),
    ]
