# Generated by Django 5.2.2 on 2026-01-03 09:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail_project', '0029_exportsession_exportpage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportsession',
            name='format_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('word', 'Word Document'), ('xlsx', 'Excel Workbook')], help_text='Output format (PDF or Word)', max_length=10),
        ),
        migrations.CreateModel(
            name='ItemConversionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('market_unit', models.CharField(help_text='Satuan pembelian dari supplier (e.g., batang, zak, dump_truck)', max_length=50)),
                ('market_price', models.DecimalField(decimal_places=2, help_text='Harga per satuan market', max_digits=18)),
                ('factor_to_base', models.DecimalField(decimal_places=6, help_text='1 market unit = X base units (e.g., 1 batang = 10 kg)', max_digits=12)),
                ('density', models.DecimalField(blank=True, decimal_places=6, help_text='Massa jenis (kg/m³) for volume-to-mass conversion', max_digits=12, null=True)),
                ('capacity_m3', models.DecimalField(blank=True, decimal_places=6, help_text='Kapasitas per market unit dalam m³', max_digits=12, null=True)),
                ('capacity_ton', models.DecimalField(blank=True, decimal_places=6, help_text='Kapasitas per market unit dalam ton', max_digits=12, null=True)),
                ('method', models.CharField(choices=[('direct', 'Direct Input'), ('calc', 'Calculated'), ('hybrid', 'Hybrid')], default='direct', max_length=10)),
                ('harga_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversion_profile', to='detail_project.hargaitemproject')),
            ],
            options={
                'verbose_name': 'Item Conversion Profile',
                'verbose_name_plural': 'Item Conversion Profiles',
            },
        ),
    ]
