# Generated by Django 5.2.4 on 2026-01-09 03:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail_project', '0030_add_item_conversion_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PekerjaanTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Nama template (e.g., 'Template Rumah Sederhana Tipe 36')", max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='Deskripsi singkat template')),
                ('category', models.CharField(choices=[('rumah', 'Rumah'), ('ruko', 'Ruko'), ('infrastruktur', 'Infrastruktur'), ('utilitas', 'Utilitas'), ('lainnya', 'Lainnya')], default='lainnya', help_text='Kategori template untuk filtering', max_length=20)),
                ('content', models.JSONField(help_text='Hierarchical data: {klasifikasi: [{name, sub: [{name, pekerjaan: [...]}]}]}')),
                ('is_public', models.BooleanField(default=True, help_text='If True, visible to all users. If False, only creator can see.')),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Track how many times this template has been imported')),
                ('total_klasifikasi', models.PositiveIntegerField(default=0)),
                ('total_sub', models.PositiveIntegerField(default=0)),
                ('total_pekerjaan', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Template Pekerjaan',
                'verbose_name_plural': 'Template Pekerjaan',
                'ordering': ['-usage_count', '-created_at'],
                'indexes': [models.Index(fields=['category', '-usage_count'], name='detail_proj_categor_d536f7_idx'), models.Index(fields=['is_public', '-created_at'], name='detail_proj_is_publ_c78d8f_idx')],
            },
        ),
    ]
