# Generated by Django 5.2.4 on 2026-01-12 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detail_project', '0034_add_weekly_progress_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pekerjaanprogressweekly',
            new_name='detail_proj_project_09cacf_idx',
            old_name='idx_ppw_project_pekerjaan',
        ),
    ]
