# Generated by Django 5.2.11 on 2026-02-08 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail_project', '0035_rename_idx_ppw_project_pekerjaan_detail_proj_project_09cacf_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailahspaudit',
            name='pekerjaan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='detail_project.pekerjaan'),
        ),
    ]
