# Generated by Django 5.2.11 on 2026-02-11 02:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_alter_project_owner'),
        ('detail_project', '0036_alter_detailahspaudit_pekerjaan'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectComputedParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Kode variabel turunan (lowercase, no spaces)', max_length=100)),
                ('expression', models.TextField(help_text='Formula turunan, contoh: panjang_l1 * lebar_l1')),
                ('label', models.CharField(blank=True, help_text='Label tampilan UI', max_length=200)),
                ('unit', models.CharField(blank=True, help_text='Satuan output formula', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Deskripsi opsional')),
                ('project', models.ForeignKey(help_text='Project owner', on_delete=django.db.models.deletion.CASCADE, related_name='computed_parameters', to='dashboard.project')),
            ],
            options={
                'verbose_name': 'Formula Parameter Project',
                'verbose_name_plural': 'Formula Parameter Project',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['project', 'name'], name='detail_proj_project_31b1f6_idx')],
                'unique_together': {('project', 'name')},
            },
        ),
    ]
