# Generated by Django 5.2.11 on 2026-02-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail_project', '0037_projectcomputedparameter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectparameter',
            name='value',
            field=models.DecimalField(decimal_places=3, help_text='Nilai parameter (numeric)', max_digits=18),
        ),
    ]
