# Generated by Django 5.2.11 on 2026-02-11 15:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_alter_project_owner'),
        ('detail_project', '0038_alter_projectparameter_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prefix', models.CharField(help_text='Opaque prefix: bp or cp', max_length=4)),
                ('last_num', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_sequences', to='dashboard.project')),
            ],
            options={
                'indexes': [models.Index(fields=['project', 'prefix'], name='detail_proj_project_6f5f3f_idx')],
                'unique_together': {('project', 'prefix')},
            },
        ),
    ]
