# Generated by Django 5.2.11 on 2026-02-11 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_alter_project_owner'),
        ('detail_project', '0039_parametersequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterMigrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_name', models.CharField(max_length=100)),
                ('new_name', models.CharField(max_length=100)),
                ('param_type', models.CharField(choices=[('base', 'Base'), ('computed', 'Computed')], max_length=10)),
                ('migrated_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_migration_logs', to='dashboard.project')),
            ],
            options={
                'indexes': [models.Index(fields=['project', 'param_type'], name='detail_proj_project_e046e5_idx'), models.Index(fields=['project', 'old_name'], name='detail_proj_project_1ffd24_idx')],
                'unique_together': {('project', 'old_name', 'new_name', 'param_type')},
            },
        ),
    ]
