# Generated by Django 5.2.11 on 2026-02-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail_project', '0042_templateahspkoefformulastate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectparameter',
            name='value',
            field=models.DecimalField(decimal_places=9, help_text='Nilai parameter (numeric)', max_digits=24),
        ),
    ]
