# Generated by Django 5.2.11 on 2026-02-19 00:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail_project', '0043_alter_projectparameter_value_precision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailahspexpanded',
            name='koefisien',
            field=models.DecimalField(decimal_places=12, help_text='Koefisien final setelah expansion (sudah dikali multiplier)', max_digits=18, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='detailahspproject',
            name='koefisien',
            field=models.DecimalField(decimal_places=12, max_digits=18, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='projectparameter',
            name='value',
            field=models.DecimalField(decimal_places=12, help_text='Nilai parameter (numeric)', max_digits=24),
        ),
    ]
