# Generated by Django 5.2.4 on 2026-06-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail_project', '0044_expand_precision_koef_and_params'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pekerjaantemplate',
            name='is_public',
            field=models.BooleanField(default=False, help_text='If True, visible to all users (admin-curated). If False, only creator can see.'),
        ),
    ]
