# Generated by Django 5.2.4 on 2026-06-15 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail_project', '0045_alter_pekerjaantemplate_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailahspexpanded',
            name='source_signature',
            field=models.CharField(blank=True, help_text='Hash nilai source raw saat ekspansi (deteksi stale, bypass-proof). NULL=legacy.', max_length=40, null=True),
        ),
    ]
