# Generated by Django 5.2.4 on 2026-06-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail_project', '0048_repair_expanded_source_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailahspproject',
            name='ref_snapshot_signature',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='detailahspproject',
            name='ref_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
