# Generated by Django 5.2.4 on 2026-06-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_alter_project_owner'),
        ('detail_project', '0050_backfill_ref_snapshot_signature'),
        ('referensi', '0024_alter_ahspimportstaging_segment_type'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='detailahspexpanded',
            constraint=models.CheckConstraint(condition=models.Q(('koefisien__gte', 0)), name='detailexpanded_koef_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='detailahspproject',
            constraint=models.CheckConstraint(condition=models.Q(('koefisien__gte', 0)), name='detailahsp_koef_nonneg'),
        ),
    ]
